### ISSUE TITLE
Reason codes in client-initiated revocation

### ISSUE THREAD

**Issue by schoen** [letsencrypt/acme-spec#101]
It would be helpful to allow the client to express a reason why it's requesting revocation when it does. (CRLs and OCSP have reason codes so that CAs can explain why a cert was revoked, but currently we don't have a way to express this from the client to the CA.)

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
