### ISSUE TITLE
Challenge Resources and Updates

### ISSUE THREAD

**Issue by jdkasten** [letsencrypt/acme-spec#105]
As the client solves various challenges (for potentially multiple identifiers at the same time) it is currently difficult to check the status of a particular challenge within the authorization resource.

Currently a GET request isn't defined for challenge resources, and there isn't a clear key for challenges within the authorization resource.  There can potentially be multiple challenges of the same type, challenges are updated with response information, but not all responses require unique information, the original challenge resource URI may vanish from the authorization resource as it is being finalized, and the size/order of the challenges array is not guaranteed so you cannot index into the array.

I see two obvious solutions
1.  Provide a key for challenges that can be referenced within the authorization resource.
2.  Allow a GET request to receive the updated status for a challenge resource.

A solution is required to create any sane generic ACME client.  The client might not be able to solve all challenges at once and may have to block until the ACME server validates particular challenges.

**Comment by pde** [comment]
Option (2) seems slightly more elegant to me but I don't have a strong opinion. We should just pick one method, implement then spec it.

**Comment by jdkasten** [comment]
I also like option 2 the best.

**Comment by kuba** [comment]
I don't think the solution is required to create any sane generic ACME client. The way I understood it, you can expect `AuthorizationResource.status == VALID` whenever server validated at least one full combo set and hence the polling code in https://github.com/letsencrypt/lets-encrypt-preview/blob/master/letsencrypt/client/network2.py#L385-438. Simply said, blocking does not require `GET challenge`.

Would `GET challenge` be just another way of tracking the progress (blocking until cert issuance request is started), or could it help the client influence the validation process? If it's just for progress, then solution 1. seems better (no duplicate functionality).

**Comment by jdkasten** [comment]
It isn't just for progress.  A challenge's status should absolutely influence the validation procedure.  You need to know which challenges you succeeded with vs. failed.

Here is one example.  If you failed the recovery token challenge twice, perhaps the user doesn't actually know the expected recovery token.  Maybe you should have them solve the recovery contact challenge.  (Having them attempt to solve recovery_token makes the entire validation procedure fail every single time when there is another way to solve the authorization.)

I would expect a "sane client" to transition to a different challenge type.  I have designed for this functionality in the https://github.com/letsencrypt/lets-encrypt-preview client
 
If we can respond to challenges individually, why wouldn't we be able to see the status of those challenges individually, or why would you include that information at all.  If a human reads the json, they can understand it... but you can't easily write a program to use that information.  That seems nonsensical to me.

By "generic" client I mean...1. We don't know which challenges will actually be involved in the future. 2. We don't know how the plugin (challenge responder) will be able to handle the challenges.

It is entirely possible that solving a challenge will require resources to be used which may inhibit other challenges from being solved.  For instance, this may be true depending on the implementation of the DVSNI challenge.  They can only put up a set number of challenge certificates  at a time and they must wait for validation of one, before they can proceed to the next.

**Comment by bifurcation** [comment]
The spec currently includes a way to do this:
```
| Poll for status | GET authz | 200 |
```

**Comment by kuba** [comment]
The question was about allowing `GET authz?chall=ID`, not `GET authz`. Please reopen.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
