### ISSUE TITLE
Imprecise wording for `POST challenge` response

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#110]
`The server updates the authorization document by updating its representation of the challenge with the response fields provided by the client. The server MUST ignore any fields in the response object that are not specified as response fields for this type of challenge. The server provides a 200 response including the updated challenge.`

I think the word "including" is confusing here and might lead to belief that the spec is contradicting itself. Boulder implemented it so that the response is Authorization Resource including the updated challenge (https://github.com/letsencrypt/boulder/issues/130). I understood this as "The server provides a 200 response containing (only) the updated challenge resource", which would make it consistent with the diagram from the spec (there is an "up" link for the challenge). Since you are able to answer challenges separately, I would expect the response to be symmetrically "separate", i.e. response should be Challenge Resource instead of Authorization Resource. (cross posted from https://github.com/letsencrypt/lets-encrypt-preview/pull/362#discussion_r29407123)

**Comment by martinthomson** [comment]
...with the updated challenge as the payload body.

**Comment by martinthomson** [comment]
...with the updated challenge as the payload body.
