### ISSUE TITLE
Recovery Tokens (secrecy), multiple authorizations

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#115]
This is a follow up on #114 and IRC discussion. It took me some time to understand the following scenario, so I really think the specification should be more clear...

- Consider account `K1` that has been granted recovery token `R`. `K1` registers two identifiers `D1` and `D2`. Client then loses `K1` but keeps the `R`.
- Client creates fresh new `K2` **for which fresh new recovery token `R2`** is created. Spec is missing that **tokens cannot be reused**.
- `K2` then tries to register `D1`. Specification should make it clear, that at this moment client will be presented with Authorization Resource in which every combination in the combinations set contains a `RecoveryToken` challenge, e.g. `{{DVSNI, RecoveryToken}, {SimpleHTTPS, RecoveryToken}}`.
- It should be spelled out that `RecoveryToken` challenge is only available if new account key tries to authorize already registered identifier. I think it is extremely confusing to present the first example of Authorization Resource containing recovery token challenge response.
- Moreover, it should be made explicit that from this moment ACME server should automatically associate `D2` with `K2`, without any further action from the client.

Sorry if the following scenario it's too complicated/confused.

cc @jdkasten

**Comment by bifurcation** [comment]
In order to be resistant to ACME MitM, we can't have token-based recovery.  So this is OBE.
