### ISSUE TITLE
The signature construction is a little worrying.

### ISSUE THREAD

**Issue by agl** [letsencrypt/acme-spec#12]
(Or, at least, it's not obviously sound.)

In section 5.2, an nonce is defined as

> A signer-provided random nonce of at least 16 bytes, base64-encoded.  (For anti-replay.)

That suggests that the nonce's length is >= 16 bytes. Later, the input to the signature algorithm is defined as:

> signature-input = nonce || content

This means that, if I capture a signature with nonce `n` and contents `abc` then I can create a signature of any suffix of `abc` by appending the unwanted prefix to the nonce.

For example, a signature of nonce "0123456789012345" and content "Hello, world" is also valid as a signature of "world" if I set the nonce to "0123456789012345Hello, ", it appears.

I suggest that the length of the nonce be fixed at 16 bytes and not controlled by the signature submitter.

(Also consider other situations in the protocol where values are simply concatenated before signing and ponder the ambiguity that arises.)

Lastly, please consider requiring that TLS server key and the ACME "Authorized Key Pair" are not equal. Some clients might save a key generation by doing that because it doesn't seem obviously wrong. However, a key installed as a TLS server key will sign an attacker's chosen 32-byte prefix at will via the TLS ServerKeyExchange message. That gives an attacker a worrying amount of control if the TLS key were also an "Authorized Key Pair" in this protocol.

**Comment by frasertweedale** [comment]
Switching to JOSE does solves this problem and would not require fixing the nonce length.

It is a sensible move anyway - why devise a new signature scheme?  I don't buy the argument that it is overkill.  Implementing support for a custom signature format seems like overkill :)

**Comment by martinthomson** [comment]
The use of JWS is sufficient to address this problem.
