### ISSUE TITLE
Allow disclaiming an authorization

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#120]
If someone gives up a domain, they should be able to disclaim authorizations they hold for it. Similarly if an entity is managing domains under various ACME accounts, and wants to transfer a domain from one account to another, they should be able to disclaim the original domain's authorization from the transferring account.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
