### ISSUE TITLE
Section 6.6. DNS: Does the server follow CNAMEs / recurse?

### ISSUE THREAD

**Issue by jcjones** [letsencrypt/acme-spec#123]
Section 6.6. for DNS validation does not specify what should occur if the resolver encounters a CNAME for a given host, namely whether to follow the CNAME or not.

Some hosting providers that may want to use DNS validation only control the DNS entries on the other side of CNAME, so for maximum automation it makes sense to recurse, at least a certain number of times, though the security ramifications are not clear to me.

**Comment by bifurcation** [comment]
*Not* following CNAMEs would require the server to not follow the standard DNS resolution algorithm.  Given that ACME servers will probably use standard resolution libraries, it seems safe to assume that they will follow CNAMEs.
