### ISSUE TITLE
Relative links

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#128]
All of the examples use absolute links, e.g. `Link: <https://example.com/acme/ca-cert>;rel="up";title="issuer"`. Are relative links allowed?  If so, then this should be made explicit.

E.g. I've naively implemented `letsencrypt` client to expect them to be absolute, which doesn't play well with latest Boulder commits.

**Comment by bifurcation** [comment]
RFC 5988 allows any URI to be included in a Link header field, including relative URIs.
