### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#129]
Spec should require that clients provide a meaningful user agent that identifies the client software and version number.

**Comment by stbuehler** [comment]
Any client could fake any user agent, so this wouldn't improve security in any way (if you think about putting it in the audit log for example). Therefore I see no value in such requirement, and most people would probably just ignore it.

**Comment by jsha** [comment]
The goal of the requirement is not security, but planning. When deprecating older versions of the protocol, we would like to know how many clients will break.

**Comment by ekr** [comment]
I don't think this is a useful requirement. There is a huge amount of User-Agent lying in the Web environment and I'm not sure we want to encourage that here.

**Comment by jsha** [comment]
How do you propose to make decisions on protocol migrations?

Would you be happier if it were a SHOULD rather than a MUST?

**Comment by ekr** [comment]
I would be happy to have a protocol version. I think it's a mistake to have a user-agent string.

**Comment by ekr** [comment]
Given that we have versioned APIs, is there a reason why we can't just measure the number of people who hit the vN versus vN+1 endpoint?

**Comment by stbuehler** [comment]
I guess I missed the versioned API so far (is it new?); I also though about suggesting a protocol version the client would send, but I think most clients would just sent the newest version they can get away with, even if they don't actually support it, if it is needed to get access to some new feature.

So I guess the bottom line is: don't put too much value into such information - keep the API stable/compatible unless you really *have* to break it - and if you have to break it, don't hesitate to do so.
(Apart from that a SHOULD sounds better than a MUST, yes)

**Comment by martinthomson** [comment]
The advice I've received, and now give, is that you don't version like that.  If you need to make breaking changes, make a new protocol at a new URI.

If the concern is that clients might be duped into sending an acmev2 request to an acmev1 server because they look quite similar, then bake something into the payload in a way that breaks the signature if it is wrong.

**Comment by bifurcation** [comment]
I agree with @ekr and @martinthomson that this is not useful.  Closing.

**Comment by ebekker** [comment]
Is there any value in have a voluntary UA string (SHOULD not MUST) simply for statistics?
