### ISSUE TITLE
SAN with wildcard domains?

### ISSUE THREAD

**Issue by webtoolbox** [letsencrypt/acme-spec#132]
I read that you will be supporting wildcard certificates. However, will it be possible to have a SAN certificate with multiple wildcard domains?

ie: *.a.com, *.b.com, and *.c.com all on one certificate?

We would require that to be able to use lets encrypt because Amazon load balancers only allow you to specify one SSL certificate and we need to secure multiple different wildcard domains.

We host forums for clients on various different domains. ie: client1.forumchitchat.com and client2.forums.com. The username the client chooses becomes part of their domain name, so using wildcards would be required.

We need to be able to use a SAN certificate to secure multiple wildcard domains.

Thank you.

**Comment by bifurcation** [comment]
It is possible to specify multiple wildcard domains in a single certificate.  This is supported by the specification as-is, but it will be up to individual CAs to decide whether they are willing to issue these certificates.
