### ISSUE TITLE
New-cert response should offer JSON responses

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#135]
The new-cert endpoint offers a DER response with a binary stream by default. For some clients it may be easier to read JSON with a field named `certificate` containing the base64url encoded DER form of the certificate.

**Comment by bifurcation** [comment]
I would want a more detailed use case before adding this complexity.

**Comment by dabraham02124** [comment]
First off, is it much extra complexity to add a function that captures the call if the accepts header is "application/json", and if so, wraps the other call?  Using jersey it would be a separate three line method, I don’t know how it would work in go.

Second, without this ticket, any client needs to manage two different possible formats of response.  What I’m doing is I’m examining the headers, and if the content type does not equal "application/json", then I read it as though it’s binary.  Then I create json of {“data”:”{base 64 url encoded version of the binary stream}”}, and pass it back up through my normal channel.

If I don’t do that, I’d have to have two paths through to handle the different encodings, and high level code like “getCertificate” would have to know the details of whether the low level code returns binary or json.


Also, is there a list of which calls don’t return json?  If it’s just the one call, then that’s a code smell.  If there’s more than one, then there should be an easily interrogated list somewhere.


Also, there’s a sub-issue (though this might be an issue for boulder?), currently new-cert returns without a content type header.  When you’re returning binary, I believe that you should set content type to "application/octet-stream”.   https://www.ietf.org/rfc/rfc2046.txt says “The subtype "octet-stream" is to be used in the case of uninterpreted binary data, in which case the simplest recommended action is to offer to write the information into a file for the user.”

**Comment by bifurcation** [comment]
The only reason we would need a JSON response is if we wanted to attach some additional information -- which we can always add with a Link relation anyway.  I agree that the server should return a "Content-Type: application/pkix-cert", but that is a Boulder issue.
