### ISSUE TITLE
Re-add contact-based recovery

### ISSUE THREAD

**Issue by bifurcation** [letsencrypt/acme-spec#136]
The recoveryContact challenge method got dropped when we moved recover to the registration level.  We should still allow people to use their contacts for recovery.  We probably want to do something like the following:

* Client submits POST to new-reg with recoveryContact attribute
* Server verifies that recoveryContact is known, returns something like 202 Accepted
* Server sends challenge to contact / client responds
* Client re-submits the same POST, gets 201 Created

**Comment by jsha** [comment]
Both this and the recoveryToken challenge added in https://github.com/letsencrypt/acme-spec/pull/137 mean we are combining multiple actions into one endpoint. A POST to `/acme/new-reg` could mean one of three things:

 - Create a new registration.
 - Update an existing registration.
 - Send me an email with a token.

The server would switch between these based on which fields are present in the posted message. I've worked on systems that had differing behavior based on the presence of a subset of fields, and it gets messy and error-prone fast.

I think it would be much cleaner to explicitly specify a message type, e.g.:
```
POST /new-registration
{ type: 'new-reg',
  contact: [ 'mailto:foo@bar.com' ] }

POST /new-registration
{ type: 'recover',
  recoveryToken: 'weohevu93kl' }

POST /new-registration
{ type: 'requestRecoveryToken',
  recoveryContact: 'foo@bar.com' }
```
