### ISSUE TITLE
Domain name ownership change

### ISSUE THREAD

**Issue by matjon** [letsencrypt/acme-spec#141]
Hello,
Let's suppose that:

1. Alice registers a new domain name, say `myfundomain.net`,
2. Alice gets a certificate for myfundomain.net (using ACME),
3. Alice loses interest in the project and lets myfundomain.net expire.
4. Bob has a similar idea and buys myfundomain.net from a reseller (possibly without knowing anything about Alice).
5. Bob wants to use ACME to get a certificate for myfundomain.net (with the same domain provider as Alice, this will be realistic when/if *Let's encrypt* really takes of).

Now Bob is unable to get a certificate for myfundomain.net because he does not have Alice's private key nor her recovery token and Alice's recovery contact is invalid for him.

**Comment by stbuehler** [comment]
I think it's up to the CA policy to find a solution for this problem - for example by requiring stronger challenges (DNSSEC signed dns challenge) instead of simpleHttps/dvsni, or notifying the original contact and giving them some time to reject the new authorization.

**Comment by bifurcation** [comment]
I agree; this is an implementor issue, not a protocol issue.
