### ISSUE TITLE
Partial revocation

### ISSUE THREAD

**Issue by ekr** [letsencrypt/acme-spec#143]
The current specification says:

"Before revoking a certificate, the server MUST verify that the account key pair used to sign the request is authorized to act for all of the identifier(s) in the certificate. The server MAY also accept a signature by the private key corresponding to the public key in the certificate."

Is this really what we want? Is there any way to lose authorization but not have the certificate revoked and narrowed?

**Comment by bifurcation** [comment]
Right now, the only way to lose authorization is for the authorization to expire -- there is no revocation.  And certificates MUST expire before any of the underlying authorizations expire (we may need to clarify this).  So you never end up in a situation where your certificate is still valid, but your account key has lost authorization.
