### ISSUE TITLE
Discuss merits of acmePath in anti-replay mechanisms

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#147]
In https://github.com/letsencrypt/acme-spec/pull/140, @bifurcation has objections to the `acmePath` provision that we didn't fully reach consensus on. This ticket is to discuss the alternatives.

**Comment by ekr** [comment]
Perhaps we should start by discussing what security properties this is intended to provide.

**Comment by jsha** [comment]
Given an attacker who can intercept, block, and modify messages, that attacker should not be able to intercept and block a message POSTed to `/foo`, then send the same request body to `/bar` and have the server process it.

**Comment by ekr** [comment]
Assuming I understand the threat model correctly this means that the attacker needs to be have control of the channel. When combined with PR #138, wouldn't such an attacker be able to insert their own URLs into the URL list, thus convincing the client to generate requests which it thought were for one URL which actually were or another.

**Comment by ekr** [comment]
s/or another/for another/

**Comment by jsha** [comment]
That's a very good point, and it's true with the current version of the protocol: The attacker can rewrite Link headers pointing to the various resources.

I don't have a great solution. One approach would be to start signing the server responses as well, but at that point we are really re-doing a lot of the work that TLS is intended to do.

**Comment by bifurcation** [comment]
@jsha and I discussed in person, and the consensus was that the "resource" field was a better solution.
