### ISSUE TITLE
Initial anti-replay nonce

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#150]
According to the current spec: `An ACME server MUST include an Replay-Nonce header field in each successful response to a POST it provides to a client, with contents as specified below.`, but how does one retrieve the initial nonce when no previous POST request has been done?

https://github.com/letsencrypt/boulder/pull/325 and https://github.com/letsencrypt/lets-encrypt-preview/pull/490 send `HEAD` to any POST URI.

**Comment by martinthomson** [comment]
I think that you are required to attempt the request, at which point it fails and you can acquire the nonce.  If you want to save on signing, I believe that the guidance should be that you send an OPTIONS request.  I can't imagine clients needing CORS preflight requests here, but maybe that conveniently doubles up with those.

**Comment by kuba** [comment]
I should have extended the quote by sentence following it: `It MAY also provide one in an error response.`, which IMHO contradicts "attempt the request" way.

**Comment by diafygi** [comment]
The boulder [test suite](https://github.com/letsencrypt/boulder/blob/master/test/js/test.js#L160) and my [nosudo](https://github.com/diafygi/letsencrypt-nosudo/blob/master/sign_csr.py#L72) script makes a HEAD request to get the initial nonces. The nonce header still comes through with a HEAD request (even though a 405 HTTP code is returned).

```
$ curl -v -X HEAD "http://127.0.0.1:4000/acme/new-reg"
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 4000 (#0)
> HEAD /acme/new-reg HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:4000
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< Content-Type: application/problem+json
< Replay-Nonce: b8uKYF8UOrqdSink3eHdVt7cm3X_6MsiseUMYGgdk4E
< Date: Thu, 11 Jun 2015 22:33:56 GMT
< Content-Length: 65
```

**Comment by bifurcation** [comment]
Addressed in #142

**Comment by martinthomson** [comment]
@diafygi do you have a boulder issue open on the 405 status code use?

**Comment by kuba** [comment]
@bifurcation, I don't think this has been resolved, please reopen. Referenced #142 does not provide info on how to get the initial nonce (first contact with the server).

**Comment by diafygi** [comment]
@martinthomson I'm not sure what you mean. A 405 response is technically correct, since the method is not allowed (it just happens to also include an anti-replay nonce).

Should boulder allow HEAD requests and return a 200 OK? There's nothing in the acme spec for HEAD requests.

**Comment by diafygi** [comment]
I agree with @kuba that this is an unresolved issue. The spec should really clarify the exact method for getting the initial anti-replay nonce. Please re-open.

**Comment by diafygi** [comment]
One suggestion: Specify a fixed "/terms" location in the ACME spec. That way, in order to get the initial anti-replay nonce, you could just GET /terms (and then you also have the terms). Boulder already has GET /terms built in, so all that's needed is adding the endpoint to the spec.

**Comment by bdaehlie** [comment]
Re-opening in order to answer new questions.

**Comment by bifurcation** [comment]
The right thing here is probably just to use the directory URI that @jsha's
PR adds.  Let's get that landed, then I'll fix this one.
