### ISSUE TITLE
GET requests should require Authorization header

### ISSUE THREAD

**Issue by diafygi** [letsencrypt/acme-spec#155]
There are three GET requests in boulder right now (authorizations, challenges, and certificates):

* `GET /acme/authz/asdf`
* `GET /acme/authz/asdf?challenge=0`
* `GET /acme/cert/123`

However, none of these require any sort of authentication, so anyone with the id of the object can see the contents. Boulder even tries to [censor](https://github.com/letsencrypt/boulder/blob/9af2742ae21cf75ba661d49d64fd47714d6a8912/wfe/web-front-end.go#L772) the object because of this ability. I'm not wild about having the only protection for these objects be the hope that no-one can guess the object ids.

I'm a fan of the RESTification process, but there should really be a requirement that the user is authenticated and a check is made to make sure they are authorized to see the object. This is normally done in APIs via an [Authorization header](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-auth-using-authorization-header.html). For GET requests, the Authorization header could be a [JWT](http://jwt.io/) that contains a payload of the endpoint being requested (plus the anti-replay nonce, of course).

**Comment by stbuehler** [comment]
Authentications might contain sensitive data, so perhaps they shouldn't be public; similar to other resources a POST with a JOSE signed empty object could be used instead of a GET.

I see no reason to keep the certificates private though.

**Comment by diafygi** [comment]
What's the policy on disclosing issued certs outside of Certificate Transparency? The ids for certs are just the serial number that's [incremented and predictable](https://github.com/letsencrypt/boulder/blob/01c41c1bd0b17efab05e414a9f9d7c23feeabfb8/test/mocks.go#L31), so someone could just scan the cert endpoint to get all the certs that the CA has issued.

**Comment by bifurcation** [comment]
The decision to not protect GET requests in general is deliberate.  The spec notes that registrations in particular should not allow GET requests, for this reason.  Specific CAs can add their own requirements on top of what the protocol requires (e.g., using HTTP authentication).
