### ISSUE TITLE
Recovery Token can be read by MitM attacker

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#157]
We assume in our threat model that ACME client <-> server connections will be MitM'ed by someone outside the secure CA datacenter, typical by a CDN. We try to mitigate this with signing of messages sent from client to server, anti-replay nonces, and URL bindings. However, such a MitM attacker can read all messages between client and server, so any information requiring confidentiality is exposed. The recovery token requires confidentiality, but can be read by the attacker and used to change account state.

**Comment by bifurcation** [comment]
This will be addressed by #156
