### ISSUE TITLE
DNS Challenge: limit the number of available characters

### ISSUE THREAD

**Issue by matjon** [letsencrypt/acme-spec#16]
Hello,
In the DNS Challenge (section 6.6) it is specified that the token MUST contain only ASCII characters:

>In response to this challenge, the client first MUST verify that the token contains only ASCII characters. 

It may be good to reduce the characters permissible in the token to only alphanumeric ones (or possibly also other used in Base64). Full ASCII range is really unnecessary here.

There have been instances of [people doing strange things with DNS records](http://zoczus.blogspot.com/2014/05/how-reverse-dns-can-help-us-with-xss.html). Note: that blog post details XSS in PTR records and is not directly relevant here.

**Comment by martinthomson** [comment]
#160 should consider this bug.
