### ISSUE TITLE
Add a section on validating identifiers

### ISSUE THREAD

**Issue by martinthomson** [letsencrypt/acme-spec#163]
When a client requests authorization for any identifier, there are a set of checks that the server needs to do on those names before progressing.

For domain names, the spec should cover the basics:
* is this a valid sequence of dns labels (characters, length of each, overall length)
* if the leftmost label is a '*', then flag that appropriately
* is the name on the PSL

**Comment by bifurcation** [comment]
This seems like it's not a protocol issue, just a question of server policy.  It might still be good to provide some recommendations.
