### ISSUE TITLE
Re-add recovery tokens

### ISSUE THREAD

**Issue by bifurcation** [letsencrypt/acme-spec#167]
#156 removed recovery tokens because they were vulnerable to MitM attacks on the ACME channel.  We should re-add a recovery token mechanism that does not have this weakness.

**Comment by kuba** [comment]
Did you really mean to close this issue? Are we not going to re-add recovery token? Why?

cc: @jdkasten

**Comment by jdkasten** [comment]
The recovery token became the recovery key mechanism.
https://letsencrypt.github.io/acme-spec/#rfc.section.6.4.1

**Comment by kuba** [comment]
Ok, thanks, @jdkasten.
