### ISSUE TITLE
Add a complete set of examples

### ISSUE THREAD

**Issue by bifurcation** [letsencrypt/acme-spec#171]
For implementors, it would be helpful to provide examples of all the transactions involved in ACME.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
