### ISSUE TITLE
Require second key pair for DVSNI

### ISSUE THREAD

**Issue by martinthomson** [letsencrypt/acme-spec#174]
Currently, the DVSNI challenge requires that the challenge respondent use the account key to authenticate the TLS connection.  This either forces the account management to be on the machine that responds to a challenge, or you need to pass private keys around.  A second key should be provided by the client for this purpose so that these keys can be separate.

**Comment by jdkasten** [comment]
Agreed. I can submit a PR with the rest of the proposed cleanup tonight.

**Comment by jdkasten** [comment]
This should be fixed in #180 following the format of the DNS challenge as suggested.  Thanks @martinthomson
