### ISSUE TITLE
Clarify replay risks

### ISSUE THREAD

**Issue by bifurcation** [letsencrypt/acme-spec#184]
The "resource" field limits replay to be within a resource class, but doesn't protect against redirection within a class.  In the current spec, that doesn't present any risks:
- Consider "noun" and "verb" resources separately
  - Noun: reg, authz, challenge, cert
  - Verb: new-reg, new-authz, new-cert, recover-reg, revoke-cert
- For "verb" resources, there's no issue -- there's only one of each (logically)
- For "noun" resources, only an issue when you POST to them
  - cert, authz never get POST
  - reg is uniquely identified by the account key
  - all current challenges have a token as unique ID

We should consider whether there's a need for some clarification around this.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
