### ISSUE TITLE
Server should be able to specify multiple "up" links per cert resource

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#185]
There may be multiple valid cert chains for a given leaf cert, and the server should be able to specify more than one of them. This is especially useful in the case of cross-signing.

The client can then make choices about which chain to offer based on its knowledge of the most commonly installed roots in browsers. Ideally, we should specify that the server can provide a hint to its "most preferred" chain by putting that chain first.

**Comment by bifurcation** [comment]
This is already possible.  The only thing the spec requires is that you provide one.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
