### ISSUE TITLE
Contact-based recovery should not reveal contact info to third parties

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#187]
https://github.com/letsencrypt/acme-spec/pull/169/files re-introduced contact-based recovery, with a provision that a recovery attempt should include an "anonymized" contact with part of the information replaced with asterisks. This is generally too much information to reveal about somebody's address: It's frequently easy to guess what's between the asterisks.

I think it's reasonable to require that, for recovery, people either remember the email address they gave, or try each of their email addresses.

**Comment by bifurcation** [comment]
This also means that the server doesn't have to have a pseudo-registration.  I'm OK removing this.
