### ISSUE TITLE
Response from contact-based vs MAC based recovery is inconsistent

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#189]
MAC-based:
> If those conditions are met, and the recovery request is otherwise acceptable to the server, then the recovery process has succeeded.  The server creates a new registration resource based on the base registration and the new account key, and returns it on a 201 (Created) response, together with a Location header indicating a URI for the new registration.  If the recovery request is unsuccessful, the server returns an error response, such as 403 (Forbidden).

Contact-based:
> If the recovery process has succeeded, then the server will send a 200 (OK) response, containing the full registration object (copied from the old registration).  The client may now use this in the same way as if he had gotten it from a new-registration transaction.

**Comment by bifurcation** [comment]
Contact-based actually returns a 201 as well, it's just that you have to poll it to see how it resolves.
