### ISSUE TITLE
Ensure that we have an efficient path for verifying large numbers of shared virtual host names

### ISSUE THREAD

**Issue by pde** [letsencrypt/acme-spec#190]
If a client is a webserver that hosts hundreds or thousands of virtual hosts, it may not be necessary to perform a separate Domain Validation TCP connection for each of those hostnames.  Combining many domains into a single DV exchange would be a massive performance and scalability win.

In particular, DVSNI is designed to prove administrative control over a TLS server.  So if DNS for N domains all point to a single IP, and that IP gives a DVSNI response that confirms an acme request for all N domains, we can save N-1 TCP/TLS connections.  

I haven't looked to see whether the protocol would currently be sufficient to achieve this well, but we should put it on the list of performance and scalability objectives.

**Comment by bifurcation** [comment]
I'm wary of these sorts of shortcuts.  For example, it may be the case that not every customer of a hosting provider wants the hosting provider to get a cert for them.  Requiring some action besides setting up hosting at least gives us a chance of distinguishing these cases.  (Though ultimately the hosting provider can always win.)

**Comment by ekr** [comment]
I am wary of this as well. Let's first see whether this turns out to be a problem in practice.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
