### ISSUE TITLE
Clarify GET-based renewal

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#191]
In https://github.com/letsencrypt/acme-spec/pull/168/files, there are now two types of certificate URLs:
 - the URL returned from /new-cert/
 - the canonical URL, listed in the example as /acme/cert-seq/12345

We should name each of these and describe their uses. For instance, the former could be called a "pending certificate resource," and the latter could be called a "final certificate resource." I'm not particular about the names.

The spec says that a GET to the certificate URI can trigger the server to renew the certificate, but it doesn't specify which URI to GET. If it's the latter: certificate URLs are public and will be crawled constantly, so that means that the CA will wind up renewing almost all of its certs, without the Subscriber actually requesting renewal.

If it's the former: That means that pending certificate resource URIs are acting as capability URIs and are expected to remain confidential, which we should document. Though capability URIs are in general a bad design pattern and we should avoid them.

I'd propose eliminating GET-based renewal. It will simplify the protocol. In #168, @bifurcation says that this allows keeping the account key in cold storage, and bringing it into hot storage to manually renew once a year. However, we want to encourage automated reissuance at time scales much greater than one year, which means clients need to be able to perform automated revalidation. Rather than have one flow for reissuance under a year, and a different flow that happens once a year, we should rely on automating both.

Further, assuming the account key is stored on a machine serving example.com, and is authorized only for example.com, then a compromise of the machine would allow validation and issuance for example.com regardless of whether the account key was stored on that machine. For deployments where a large number of authorizations are held on a single key, it is possible to hold that high-value key on a machine separate from the web frontends, and perform DNS validations.

**Comment by ekr** [comment]
I am not in favor of removing GET-based renewal. Yes not everyone may want to keep their account key in cold storage, but some may, and we should allow them to do so.

**Comment by ekr** [comment]
To be clear, to the extent to which the concern is crawlers generating spurious renewals, s/GET/POST/

**Comment by ekr** [comment]
To answer an offline question for @rbarnes, the requirement here seems to me to be to have reissuance be unauthenticated. In fact, what I'd actually prefer is that the CA be allowed to just auto-reissue and then garbage collect anyone who doesn't check in periodically for some local value of periodically.

**Comment by bifurcation** [comment]
As a compromise proposal, let's try to address the ambiguities and crawling risks that @jsha notes above, and leave things in a state where it's easy for a CA not to support renewal in this manner.

**Comment by martinthomson** [comment]
FWIW, I'm not concerned that GETs to the renewal resource might trigger re-issuance.  Whether it triggers a re-issuance is entirely up to the CA.  As @ekr notes, the CA might choose another trigger.  The point is that the GET to that resource always retrieves the *most recent* certificate, which might be a nice, shiny new one.

**Comment by richsalz** [comment]
We (Akamai) can securely keep the account key, and we're not worried about how often it will have to be used. I am concerned about requiring the account to be used for renewals, especially as the lifetime shrinks: it seems like the policy would reduce the exposure of the TLS key, but increase the exposure of the account key by requiring very common access to it.
