### ISSUE TITLE
define "valid" explicitly

### ISSUE THREAD

**Issue by jmhodges** [letsencrypt/acme-spec#197]
Per discussion in letsencrypt/boulder#464, "valid" needs an explicit definition. There is also some discussion there about defining "valid" as not-404ing leading to possible information leaks now or in the future as the spec is expanded.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
