### ISSUE TITLE
directory always contain FQDN urls?

### ISSUE THREAD

**Issue by jmhodges** [letsencrypt/acme-spec#199]
It's not specified, so I suppose the URLs in the directory object can be relative URLs, as well. But the example is not. Would be nice to just say one way or the other.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
