### ISSUE TITLE
Improve sample of Proof of Possession of a Prior Key

### ISSUE THREAD

**Issue by acv** [letsencrypt/acme-spec#2]
The Proof of Possession of a Prior Key section of the spec includes the following example: 

    {
      "type": "proofOfPossession",
      "nonce": "eET5udtV7aoX8Xl8gYiZIA",
      "signature": {
        "alg": "RS256",
        "nonce": "eET5udtV7aoX8Xl8gYiZIA",
        "sig": "KxITJ0rNlfDMAtfDr8eAw...fSSoehDFNZKQKzTZPtQ",
        "jwk": {
          "kty": "RSA",
          "e": "AQAB",
          "n": "KxITJ0rNlfDMAtfDr8eAw...fSSoehDFNZKQKzTZPtQ"
        }
      }
    }

From reading the text surrounding this sample, I get the impression that both "nonce" should be different and that this should be reflected in the sample.

Thanks.

**Comment by bdaehlie** [comment]
We're going to have a discussion about whether or not we are going to do proof of possession, moving this to a feature-specific milestone while we decide.

**Comment by bifurcation** [comment]
OBE given recent revisions to PoP.
