### ISSUE TITLE
Section 5.2 "Registration Objects" example omits key

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#200]
Section 5.2 specifying the formatting of Registration Objects requires a key, but no example key is given below

We should use the example key specified in [RFC 7517](https://tools.ietf.org/html/rfc7517#page-5):

``` json
     {"kty":"EC",
      "crv":"P-256",
      "x":"f83OJ3D2xF1Bg8vub9tLe1gHMzV76e8Tus9uPHvRVEU",
      "y":"x_FEzRu9m36HLN_tue659LNpXW6pCyStikYjKIWI5a0",
      "kid":"Public key used in JWS spec Appendix A.3 example"
     }
```

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
