### ISSUE TITLE
When specifying JSON resource object types, don't use 'dictionary'

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#201]
...since it's a pythonism.  Better to use `object` as specified in [RFC 4627](https://www.ietf.org/rfc/rfc4627.txt), section 1.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
