### ISSUE TITLE
Pluralize "dictionary of string"

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#202]
https://letsencrypt.github.io/acme-spec/#authorization-objects

s/dictionary of string/dictionary of strings

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
