### ISSUE TITLE
In 6.3, server instructed to ignore 'key' which it needs

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#203]
https://letsencrypt.github.io/acme-spec/#registration

Under the first JSON example, we are instructed to ignore the `key` field when posting to the new registration URI.  The next paragraph instructs us to then _use_ the `key` field when verifying subsequent JWS requests.

The example also excludes the `key` field.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
