### ISSUE TITLE
Clarity in Recovery Contact

### ISSUE THREAD

**Issue by bmw** [letsencrypt/acme-spec#204]
When a client wants to initiate contact-based account recovery, does it need to include contact information in the request? This information is included in the JSON example but is not mentioned in the spec. If it is required, this should be stated along with the server's response to invalid contact information. If not, this field should be removed from the example.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
