### ISSUE TITLE
Allow fields `resolvedAddrs` and `redirects` in challenge output

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#205]
Per https://github.com/letsencrypt/boulder/pull/505 we are recording these values as part of our validation of names. We should update the spec to allow these as part of challenges returned to the client.

**Comment by bifurcation** [comment]
@jsha Could you elaborate on the benefit of exposing these fields, and any possible privacy risks?  "Our code does it" is not a rationale for going into the spec :smile:

**Comment by jsha** [comment]
I think there aren't significant privacy issues. In order to perform the relevant validations, a server must be publicly reachable under the name to be validated. That name will shortly wind up in a cert, which will also be public. Therefore it's possible for anyone to find the IP address of the server given the name in the cert.

Further, it's useful to make these components public, as they form part of the CA's proof that it validated a given domain at a given IP. If a CA was misdirected via DNS spoofing, that can be detected publicly and reported, so that the cert can be revoked. A similar argument applies for redirects.

**Comment by ekr** [comment]
It seems like the question of which IP address out of the group was used is not necessarily the same as having a list of all the present IPs.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
