### ISSUE TITLE
Add example for why certificate keypair is sufficient for revocation

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#207]
"Revocation requests are different from other ACME request in that they can be signed either with an account key pair or the key pair in the certificate."

Add an example:

"This may be useful if, for example, the certificate private key is released as a result of server compromise, or the certificate itself was generated without sufficient entropy and thus easily factorable. In these cases, third party can request a revocation signed by the certificate even when the account holder is unavailable."

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
