### ISSUE TITLE
Clarify who example.com refers to

### ISSUE THREAD

**Issue by riking** [letsencrypt/acme-spec#208]
I was reading the spec, and it seems that it uses example.com for both the ACME server and client in the Registration object example.

Perhaps it should use `ca.example.com` and `website.example.net` instead.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
