### ISSUE TITLE
7.4 DNS Challenge *pre*pends label

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#209]
> The record provisioned to the DNS is the “signature” value from the JWS, i.e., the base64-encoded signature value. The client constructs the validation domain name by appending the label “_acme-challenge” to the domain name being validated, then provisions a TXT record with the signature value under that name.

s/append/prepend, as in the example:

`_acme-challenge.example.com. 300 IN TXT "gfj9Xq...Rg85nM"`

**Comment by jsonn** [comment]
I've stumbled over this as well. It doesn't just prepend the label, it prepends the component, i.e. it wants to query for a subdomain.

**Comment by raybellis** [comment]
In DNS terms that's what "prepending a label" means - the individual parts of a domain name are called labels, so prepending one puts a _new_ one on the front, it doesn't concatenate it with the existing left-most label.

**Comment by jsonn** [comment]
It wasn't clear that the DNS term is actually intended here due to the suffix/prefix mismatch. Cleaning that up makes the intention clearer.

**Comment by raybellis** [comment]
It's not really possible for it to mean anything else, although clearly the text should be amended to read "prepend" instead of "append".  Prepending a DNS label always results in a subdomain of the original domain - if you simply concatenated the string you'd potentially end up with `_acme-challengeexample.com`, which is of course nonsense.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
