### ISSUE TITLE
9.1 update outbound cxn methods

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#210]
> Each of the three channels, for example, uses a different communications pattern: the ACME channel will comprise inbound HTTPS connections to the ACME server, the validation channel outbound HTTP or DNS requests, and the contact channel will use channels such as email and PSTN.

s/outbound HTTP or DNS/outbound HTTP, non-validated HTTPS, or DNS requests/g

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
