### ISSUE TITLE
Differing description of {DVSNI, DNS} validation mechanism in 7.2, 9.2

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#211]
> Simple HTTP: The value provided in the validation request is signed by the account private key.
> DVSNI: The validation TLS request uses the account key pair as the server’s key pair.
> DNS: The MAC covers the account key, and the MAC key is derived from an ECDH public key signed with the account private key.

This is not the way the spec describes DVSNI validation. Is this from an older version? [Section 7.2](https://letsencrypt.github.io/acme-spec/#rfc.section.7.2) indicates that DVSNI responds to the provisioned SNI resource with JWS within the HTTP body.  Following this, it should read:

> Simple HTTP & DVSNI: The value provided in the validation request is signed by the account private key.
> DNS: The signature in the DNS response is generated using the account private key.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
