### ISSUE TITLE
Add RECOMMENDED line to stronger DNS validation

### ISSUE THREAD

**Issue by Hainish** [letsencrypt/acme-spec#212]
Reflecting the 9.2 DNS hijacking mitigation techniques, I suggest we add a line in the technical specifications portion with a stronger wording, recommending DNSSEC validation & multi-perspective DNS agreement

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
