### ISSUE TITLE
Dns challenge signature is too long for dns TXT record

### ISSUE THREAD

**Issue by r0ro** [letsencrypt/acme-spec#213]
By the latest spec, the value that should be provisioned to dns for dns validation is :

> The record provisioned to the DNS is the "signature" value from the JWS, i.e., the base64-encoded signature value

the spec also says that :

> In response to this challenge, the client uses its account private key to sign a JWS over a JSON object describing the challenge

This means that if my account key is a 4096 bits RSA key, I should end up with the following validation object:

```javascript
 'validation': {
        'header': {
            'alg': 'RS256',
            'jwk': {
                'kty': 'RSA',
                'e': 'AQAB',
                'n': '1NarLTg5X_pFa8l0Qa_bolZIeKaxUxhBTGo3Emuja4ofNqci59N4KQm9cUdb36rssFyukVGI7ncMQRK6mYoFqLqbvstHyGRwwXUF6IBQOfNBw4PnHOHbaM-uSMIXY8fIgdgRse3-5im8G34bdmy5E6UdnP9DVxb-qaytr106PQrsK9tSNUEN11XdYC3TZ0C4ZJm0HdHr9PpqF1iEXlcprQe4A1vVesBAH_W8NgRnKpo3lfVlnFaCjTab0GAfKeFYvwyD-p3fxcLyZIS8itaUL8aLdX7mKkKsqHlYHaw1HGobxWZkI_zYhgMMdCAzH_vuFBi3TFV1E8gz_TQXDHHigI9ArQER3fPnKRLdoaQ4qWrOg09LuCtcTS-SssY0JxXArhqgaw_sAIIqyX2v3Nb7K5yn7dlq6fnCQQ73qRcV-qDK2VUq_v2bqjqVPNkRI7CXfchLH82-p89dkuhm9XMXGNIy9x9EfZ4vuSUwc_nkYvl29Lu8Qcp7zQzGt59TA2Y50P8AI8j7vQtegl8ksppZ1YiOr-fBfD8A845usjSIWk9ifnzYTpp8OJzKW1KjgeSeM_gXSkcZsNjRqy69QrdgMpNaioqQSyUvCujhyoWepgFXzLrcAujWr6JwTUIhSjAM9QTs1fYUtitPxxxxB6zpAeWQKQ2fyxQh_KP0kP4vZTE'
            }
        },
        'signature': 'sJXZ6vMRgh55qGTm4ukSOQfv-CCYouV-aEC5mqq3MKqXZghUIwIU437PVQJH2KrjISxR-DdgF91E8tlapVyUW86XkH4RYKvZLHwMQ2mmU0OUu_ophaK2g94uNSRATeR8GjHxQwSO306x-Id0dj_ts3Lcnvq0rJ2YWk25hKP_cD4A99u3n7bUL-OW8IFv11QYYAGw8Ew6jA2rqQGNOBnRGR4Wko3mGGjy0e190oZDHL4YVQLXrHf0DD9v8fwiR62gejkgNZfbtg-OZ794sZwmJpKEdZADGopXvhlB0zGyIOluj3LrUPjKLPYadw6c2jOmcbMvThu7iNTmXYwFD0RBp2YYQAzc8J4xG2d_UZdF-H9VHz2iHFjnvMNguJXRs6D9paCcoQL-aSp_PcT3oV6_Yw6t_sjXpqe5lzUejvZFrplH0rKTqJ94qBIQrQY6Mwn3gVE5Dmb8qa4KlvnVf6eDjO6iKlneDSH_NWdc6hq7OuiKyGDTP8LjdBVhhYiWtzG0BWshAn-GlmTTrVHYwU5TpOfO7mRoXgtC4M0ESl2mvsASLjnuhMdw0hxDma3dq1um6e--4Jobwezyih_kytd5NUF33t1_fyPkA7Pu8Y34JI-IvXBzsNIUz48eHb7R_UICjqZGzgmxojbcz1a6SSP9YD8JX10COukmdvnsE31lG-I',
        'protected': 'e30',
        'payload': 'eyJ0b2tlbiI6ICJrRTNuQjNxN29CVG5vN2RaazhLMm1MMzZBZW9lQWU5QS01cS1BTWJ0Z1dFIiwgInR5cGUiOiAiZG5zIn0'
    }
```
Using my 4096 bits account key, I end up with a 4096 bits signature (**683 characters** once in base64)
This is a pretty long dns record that should be kept **under 255 characters**.

Since the rationale here is to ensure that the token has been signed with the account private key, we could keep the same request, but instead of using the base64 signature for the JWK for the dns value, we could use base64url(sha256(signature)). 
This way the acme server is still able to verify that the challenge reply has been signed with the account key, but we end up with a much compact TXT record.

To validate a proof-of-possession challenge, the server would performs the following steps:

1. Verify the validation JWS using the account key for which this challenge was issued
2. Decode the payload of the JWS as UTF-8 encoded JSON
3. Verify that there are exactly two fields in the decoded object, and that:
The "type" field is set to "dns"
The "token" field matches the "token" value in the challenge
4. Query for TXT records under the validation domain name
5. Verify that the contents of one of the TXT records match the base64 encoded sha256 of the JWS signature field.

**Comment by r0ro** [comment]
ref: [RFC 1035 Standard RRs] (http://tools.ietf.org/html/rfc1035#section-3.3)

> "character-string" is treated as binary information, and can be up to 256 characters in
length (including the length octet).

**Comment by rolandshoemaker** [comment]
255 characters is the single string limit, a TXT (or SPF) record may exceed this limit by using multiple quoted strings in the record which the reading application must then concatenate, [ISC Reference](https://kb.isc.org/article/AA-00356/0/Can-I-have-a-TXT-or-SPF-record-longer-than-255-characters.html)/[RFC4408](http://tools.ietf.org/html/rfc4408#section-3.1.3), i.e. `TXT "..." "..."`. If we were to use multiple records we would require a way to make sure returned TXT strings were concatenated in the right order, and that no other TXT records are present that could foul up the JWS object.

**Comment by r0ro** [comment]
Even with multiple TXT records, it requires that the dns server keeps the TXT records order, and from what I've seen during my tests, it's not always the case. Also it will most likely require to use tcp for dns queries (also not supported by all dns servers).
Using a hash of the signature offers the same level of trust, without those potential problems

**Comment by r0ro** [comment]
This will be fixed if https://github.com/letsencrypt/acme-spec/pull/223 is merged

**Comment by andrewtj** [comment]
There's a bit of misunderstanding here. TXT records may contain multiple character strings and each character string can be 0 to 255 bytes. The maximum number of character strings that can be contained within a single record is limited only by the resource record length field (RDLEN) which is 16-bits and by extension ultimately whatever else is within a given message. (Messages also have a 16-bit length limit and there's the 12-byte header, question and other RRSet fields to take into account.) The order of character strings within a given TXT record is always preserved.

**Comment by r0ro** [comment]
Yes, you are right. I figured this out by reading the spec again.
I still consider short records should be preferred, for easier configuration and maximum compatibility.
