### ISSUE TITLE
Specify type of "true" / "false" value for "tls" field.

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#214]
The spec and examples are currently ambiguous as to whether the value of the tls field should be a boolean or a string. We should use a string for maximum clarity.

**Comment by martinthomson** [comment]
If the value is a boolean, then it should use a boolean.  Why would you encode boolean values as a string?

**Comment by jmhodges** [comment]
Because many bad APIs have done that and people often expect things to be stringly-typed. Not so bad to lock it down.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
