### ISSUE TITLE
method needed for forwarding *.acme.invalid to correct server

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/acme-spec#222]
## Proposal

Include the domain for which the certificate should be granted - such as `<<challenge>>.example.com.acme.invalid` or `example.com.<<challenge>>.acme.invalid` so that it can be forwarded to the correct device when a home gateway device is managing multiple devices.
## Backstory

The last time I was making an issue on this github repo I was working on the same home cloud product I am now and I was complaining about how the DVSNI being restricted to port 443 creates problems where the application / web server (nodejs, ruby, etc) needs to stay running while the python script fetches the certs (see https://github.com/letsencrypt/acme-spec/issues/19).

I solved that using haproxy by having the `*.acme.invalid` requests forward to the running python script on `localhost:1443` using the `--dvsni-port 1443` option.
## Problem

Well, it turns out that when the home cloud is behind a dorm network, Xfinity, Google Fiber Network Box, or some other device that doesn't (properly) support UPNP requests for forwarding 443 I have to have an external reverse vpn that uses haproxy to forward the connection to the "client" trapped in such a network.

However, since many of these devices connect to a single reverse vpn, there needs to be a method to forward the requests on to the target device.
## Reasoning

I realize that I can have the rvpn / gateway device receive the certificates for itself and then forward them on to the target device by some arbitrary means after-the-fact, but then they aren't being generated by the target device. In the case that the gateway device is stolen or compromised the certificates which have been written to the hard drive could be recovered, even if they had been deleted.
## Product hitting the Market

This isn't just a hypothetical or one-off scenario. Assuming that LetsEncrypt launches on the 14th and we can switch over to using the production system, my company will be announcing our crowd funding campaign for home cloud / social cloud system towards the end of September and beta devices will begin shipping immediately.

We estimate that somewhere between 25% and 50% of our devices will land in homes that don't support UPNP properly and will thus require the assistance of a socially-trusted peer device to provide a public IP as a resource through RVPN and we don't want those certs touching the disks of devices that may at some point have their trust revoked - just to be on the safe side.
## Other suggestions?

I'm open to suggestions.

At some point we'll have to write a golang or node.js version of letsencrypt (python is so sloooooooooooow on ARM - takes about a minute for the standalone process to run), so I know I could probably do something fancy to send the token to the rvpn gateway manually so that it knows where to send it back when it matches, but I'm hoping to put that off for a little while yet.

Just got back from a hackathon and it's 4:30am, so I'm sure I skipped some words or otherwise didn't make complete sense, but hopefully you get the gist.

**Comment by coolaj86** [comment]
Better stated as https://github.com/ietf-wg-acme/acme/issues/23

**Comment by coolaj86** [comment]
Closed at https://github.com/ietf-wg-acme/acme/issues/23

**Comment by nirgal** [comment]
I am having the same issue with a setup where an haproxy acts as a htttps frontend that reads the SNI to send it to the correct server on the lan.
In case you are wondering, haproxy frontend does NOT know the certificates. Because the SNI is received in the very early stage of the connection, it is able to forward the connection to the correct without decrypting it. :)

Right now, I need to manually set a default backend for SNI hosts *.acme.invalid to the server currently renewing its certificate.
Automating this will be very ugly.
Please do not put the challenge in the SNI. Use the real servername (or support ipv6 as a work around!)

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
