### ISSUE TITLE
Register .well-known/acme-challenge with IANA

### ISSUE THREAD

**Issue by schoen** [letsencrypt/acme-spec#225]
A commenter on the forums pointed out that it would be worth registering `acme-challenge` as a well-known URI suffix

https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml#well-known-uris-1

It appears that the registration process could be done in consequence of the eventual publication of the ACME RFC, but it might also be possible to request it sooner.

**Comment by Weishaupt** [comment]
This can be closed since it is registered since 2016-08-18.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
