### ISSUE TITLE
Describe 'validationRecord' (part of a challenge-resource)

### ISSUE THREAD

**Issue by BlackGh0st** [letsencrypt/acme-spec#226]
Hi there, the current version of boulder attaches the field 'validationRecord' to a completed challenge ( part  of a "Identifier Authorization"-resource ), but I can't find any further information about this resource in the specification.

for example [Identifier Authorization Ressource]

```
{
   "identifier":{
      "type":"dns",
      "value":"example.com"
   },
   "status":"valid",
   "expires":"2016-07-13T13:13:13Z",
   "challenges":[
      {
         "type":"simpleHttp",
         "status":"valid",
         "uri":"https://acme-staging.api.letsencrypt.org/acme/challenge/asdf/1234",
         "token":"h876oasdhn897o6asd",
         "tls":false,
         "validationRecord":[
            {
               "url":"http://example.com:80/.well-known/acme-challenge/h876oasdhn897o6asd",
               "hostname":"example.com",
               "port":"80",
               "addressesResolved":[
                  "123.123.123.123"
               ],
               "addressUsed":"123.123.123.123"
            }
         ]
      }
   "combinations":[
      [0]
   ]
}
```

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
