### ISSUE TITLE
Usage of RFC3339 - "5.3 Rarely Used Options"

### ISSUE THREAD

**Issue by BlackGh0st** [letsencrypt/acme-spec#227]
Hi there, 
since the usage of nanoseconds is a 'rarely used option' in the RFC3339, I think we should explicitly say that boulder makes use of this case.

There are some languages (for example PHP) which doesn't expect an RFC3339 date to have nanoseconds. This would help some developers (like me) to pay some extra attention to this case.
- http://tools.ietf.org/html/rfc3339#section-5.3
- https://bugs.php.net/bug.php?id=64814
- http://php.net/manual/en/class.datetime.php#datetime.constants.rfc3339

**Comment by jsha** [comment]
Can you file an issue on Boulder asking about specific spots where it emits nanoseconds in RFC3339 dates? I'm sure they're unnecessary and it's probably simpler / nicer just to omit them.

**Comment by BlackGh0st** [comment]
Well, it looks like it's unnecessary to use nanoseconds, but I think the problem is more a part of go. There the default format for time objects is RFC3339Nano [1].
Would it be valid to just say that ACME MUST NOT make us the RFC3339Nano part?
 - [1] https://golang.org/src/time/time.go?s=26997:27040#L922

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
