### ISSUE TITLE
Domain validation and usage of userkey pair discussion

### ISSUE THREAD

**Issue by stonie08** [letsencrypt/acme-spec#234]
I hope this is the right issue tracker.
Some thoughts about the security of the current domain validation:
In a scenario where a server is behind a router and shares the public IP address with other users, it is currently possible to get issued a new certificate for the respective domain. This affects providers of VPN, university networks, small companies, home server admins, and the similar. This is partly because there is no check if the userkey pair is the same as the previous (I tried by creating a new pair for a new request). Eg. for people living in a shared apartment one can issue a new certificate for the homeserver by ARP spoofing the servers IP address for a short time. The same goes for guests you give your wifi password to.
Also I'm quite sure there are some small companies out there who offer internet access and run a small webserver on the same public IP address. Again anyone can issue a new certificate for the corresponding domain and even any of the co-workers can.

On the other hand pinning the userkey pair would make it a risk to buy domains, because maybe you wouldn't be able to register with LE just because the previous owner didn't unregister.
Are there any planned policies for that issue?! What's the purpose of account keys at the moment?

**Comment by jmhodges** [comment]
This, unfortunately, is not the right repo. The right one is https://github.com/ietf-acme-wg/acme-spec/

Sorry.
