### ISSUE TITLE
Letsencrypt behind a firewall with NAT

### ISSUE THREAD

**Issue by Sebi94nbg** [letsencrypt/acme-spec#240]
We're hosting our servers behind a IPfire firewall. Our public IPs are connected on IPfire and all connections will be NATed to to related server behind the firewall.

Client <-> IPfire with Alias IP for Webserver (78.11.33.231) <-> NAT Port 80 and 443 TCP to internal IP <-> 10.1.1.157

Currently, we aren't able to use Letsencrypt, due a missmatch of our host information.

I've found this community post: https://community.letsencrypt.org/t/experience-from-nat-ed-virtual-ubuntu-server-with-wp-sites-nginx/1512

But this is no solution for us. We're hosting hundreds of websites on ~80 webservers.

Is there already a solution for my scenario or not? How can we still use Letsencrypt?

BTW: We're using apache2.

**Comment by Halpha** [comment]
We have the same issue.. Is it possible to use letsencrypt with NAT?

**Comment by AlroneRhyn** [comment]
Hi Guys, is there any solution / workaround ?

Thx !

**Comment by Sebi94nbg** [comment]
I didn't found one yet, no.

**Comment by jsha** [comment]
Hi all,

This conversation should be held on the Let's Encrypt forums at https://community.letsencrypt.org/.
