### ISSUE TITLE
--agree-tos in ACME clients: acceptable or not?

### ISSUE THREAD

**Issue by fxkr** [letsencrypt/acme-spec#241]
It would be nice if it could be clarified whether "--agree-tos"-like switches in ACME clients are acceptable.

certbot has it.

On the other hand, the author of acmetool refuses to implement "--agree-tos"-like functionality without clarification in the spec, making it impossible to completely automate renewal with certbot. (https://github.com/hlandau/acme/issues/200)

**Comment by lordfolken** [comment]
I think this is the wrong place. This repo hasn't been active since 2015. Apperantly the following is current:
https://github.com/ietf-wg-acme/acme

**Comment by fxkr** [comment]
You're right, thanks!
