### ISSUE TITLE
Miscount in section 5

### ISSUE THREAD

**Issue by hagman** [letsencrypt/acme-spec#35]
Section 5 (Certificate Management) starts "In this section, we describe the <b>four</b> certificate management functions that ACME enables:" and then lists only <b>three</b> items (Key Authorization,  Certificate Issuance,  Certificate Revocation). This should be adjusted one way or the other (is 5.2 Signatures the fourth item? Or perhaps 5.3.1 Recovery tokens? Or should "four" simply be replaced with "three"?)

**Comment by bifurcation** [comment]
The "four" is no longer there in the current spec.
