### ISSUE TITLE
Advertise CA capabilities better

### ISSUE THREAD

**Issue by martinthomson** [letsencrypt/acme-spec#36]
Please consider advertising:
- the root (and intermediate) certificates that will be used
- the signature algorithms that will be offered

If there is a linkage (and there might be sometimes), then tuples of these make sense.

As PHB notes, this could be useful in determining whether to pursue a request with a CA that offers this protocol.

**Comment by jsha** [comment]
Yes, this should definitely be available. Should there also be a way for the client to request signing with a certain root, or a certain hash, or with a CT proof baked in? For instance, a single CA might offer signing with either SHA-1 or SHA-2 from the same root.

One simple approach would be to specify that a single ACME instance always signs with a single root, single hash, etc. CAs offering multiple roots or hashes would run multiple ACME instances under different paths on the same hostname, with a discovery URL listing the instances and their options.

A more complicated approach would let clients propose a set of desired attributes and let the CA fulfill the ones it can / wants to.

The former is simpler but potentially has a combinatorial explosion if there are lots of options available on a single CA. The latter is more complex, but is probably also more backwards compatible. For instance, if there are many deployed clients still asking for SHA-1 but CA policy requires only issuing SHA-2 certs, the ACME server could still serve those clients.

**Comment by martinthomson** [comment]
Note that this might not be necessary; you could have different ACME URLs for different profiles (RSA over here, ECDSA with P-256 over there).  Even with all the combinations, it's not particularly unwieldy.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
