### ISSUE TITLE
version number in PDUs

### ISSUE THREAD

**Issue by randyqx** [letsencrypt/acme-spec#43]
unless you are sure this is immutable, perhaps a version number in the pdu headers

**Comment by bifurcation** [comment]
This is immutable, in the sense that we assume that each resource (URL) will only handle requests for one version.  So the server has a set of v1 URLs, which are different from the v2 URLs, etc.  The only risk is if there are v2 PDUs that are syntactically valid in v1 with different semantics.  This is a situation that we can avoid when we design v2.
