### ISSUE TITLE
Type value should be "dns" not "recoveryToken" in section 6.6 DNS

### ISSUE THREAD

**Issue by franks42** [letsencrypt/acme-spec#44]
Both challenge and response read:

    type (required, string):
    The string “recoveryToken”

while the examples show:

    {
      "type": "dns"
      ...
    }

Presume the examples are correct and the spec should read:

    type (required, string):
    The string “dns”

**Comment by kuba** [comment]
Fixed in https://github.com/letsencrypt/acme-spec/commit/c2f49ce468605b8031556b6fdf260a201ea16aa6
