### ISSUE TITLE
Ensure there's a neat way for Authorized clients to change their Recovery mechanisms

### ISSUE THREAD

**Issue by pde** [letsencrypt/acme-spec#47]
I haven't read closely; this may be true already but if not we should add it.

**Comment by jsha** [comment]
At our meeting yesterday we discussed this issue, and the plan is to add another endpoint that registers a given keypair with a set of recovery information (contact info, recovery token). Presumably clients will be able to hit this endpoint again to change that recovery information.

**Comment by bifurcation** [comment]
This was addressed when we split registrations out of authorizations.  Just send a POST to the registration URL with your new contacts.
