### ISSUE TITLE
Recovery keys

### ISSUE THREAD

**Issue by martinthomson** [letsencrypt/acme-spec#50]
I noted this when reviewing #48.  I think that this needs a better design, since it would be good if the information hosted in the authorization resource could be all completely public.

If the design of the recovery keys is such that they could be used just once (and I think that's probably fair), then you don't need to worry about redacting anything.

Clients create an authorization resource with a recovery key by adding a "recoveryKey" challenge when they request that the resource be created.  This includes a hash value:
```
hash = HMAC(recoveryKey, 'acme-recovery\0' || identity.type.length || identity.type || identity.value.length || identity.value)
```
(I'm not sure what sort of HMAC discriminator you might want to use throughout, so details can vary.)

If a client wants to use the recovery key, it provides the value of recoveryKey.

Now, to the separate question of why it might want to have this capability at all...

**Comment by bifurcation** [comment]
I think this has been rendered moot by recent changes to the authz/registration objects.
