### ISSUE TITLE
Make timeout behavior explicit

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#54]
For authorization requests and possibly other interactions in the protocol, there will have to be timeouts. For instance, a client may need to present a challenge response within 15 minutes, or the challenge will expire and need to be restarted. The spec should make these timeouts more explicit, and specify behavior and error codes.

**Comment by bifurcation** [comment]
I think that in most cases, it will be sufficient for the server to just 404 expired challenges, and choose a sufficiently long timeout that clients will rarely hit this condition.  We can re-open this if we turn out to need a mechanism.
