### ISSUE TITLE
Simplify Proof of Possession challenge

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#56]
Ryan Sleevi pointed out recently that a Proof of Possession challenge can be risky because a malicious server can ask a client to sign some string that collides with or looks like a pre-master secret for an SSL handshake.

Additionally, the PoP challenge can be simplified to use the existing certificate validation mechanisms built into TLS. Proposal: amend PoP challenge to say:

> This challenge is the same as the SimpleHTTPS challenge, with the additional constraint the the verification request must occur over a validated TLS connection with a non-revoked certificate that contains the requested identifier.

**Comment by bifurcation** [comment]
This was addressed by #176
