### ISSUE TITLE
Clarify certificate refresh process

### ISSUE THREAD

**Issue by jsha** [letsencrypt/acme-spec#59]
Right now we specify certificate refresh as a GET URL, in response to which the server may choose to provide a refreshed certificate.

It's not specified if the server would issue the refreshed certificate in real-time. I suggest that we should specify that the server will never generate the refreshed certificate in response to /acme/cert/asdf.

 - Because certificate issuance may take more than a few seconds, which means it is longer than we want a GET request to be pending for.
 - Because, as a GET URL, it is not authenticated by the private key. That means that a third party could trigger a certificate issuance even if the account owner did not request it and is not installing the fresh certificate. This is probably not an issue, but could generate strange corner cases.

Instead, the server may choose at its discretion to periodically refresh certain certificates and have them ready to respond to GET /acme/cert/asdf. Response time would be more or less constant and there would be no risk that third party could mutate state with a GET request.

**Comment by martinthomson** [comment]
I have no problem with a real-time generation in response to the request.  That keeps the generation load low when there are no incoming requests.  Using the request to trigger generation is perfectly reasonable.  If the server is stressed, and it doesn't have a pre-made cert ready, it can always respond with a 503 and a Retry-After.

As for unauthenticated requests generating load, it's easy to check how old the current cert is before starting the new one.  I have no concerns here regarding strange corner cases.

Leave this to the discretion of implementers.  Obviously, pre-generation is going to give you the most predictable load profile, but don't force it on everyone.

**Comment by bifurcation** [comment]
+1 to what Martin said.  This is not a protocol issue, it's up to
implementors.

**Comment by bifurcation** [comment]
Thinking on this further, I've had some evolution in thinking.  I think it's pretty critical that refresh be client-initiated, probably using something like a `new-cert` transaction but specifying the base certificate and the new validity interval.
