### ISSUE TITLE
Key Pinning & Let's Encrypt

### ISSUE THREAD

**Issue by azet** [letsencrypt/acme-spec#60]
Hi,

Thanks for authoring this draft. I'll continue to submit minor editorial changes, I haven't found a flaw so far.

I have a suggestion though: at no point does the document mention key pinning (it mentions HTTPS explicitly w.r.t. DV certs. though). It might be a good idea to support TACK (or HPKP in the case of HTTP) by design. I've looked through all issues/PRs and could not find appropriate discussion on this topic. 
The only mention I see is in #17 - with @martinthomson refering to refresh rates. Does this refer to short-lived certificates? 

**edit:**
One of the deployment issues I see with key pinning techniques in general is that administrators might get the pinning wrong and basically lock-out their users for good. To people working a lot with crypto and it's toolchain it's easy, to a run-of-the-mill admin probably not so much. If that part would be automated as well, I think key pinning would see real adoption in the future.

Thanks,
Aaron

**Comment by bifurcation** [comment]
It seems like this is mostly not a protocol issue.  HPKP is the appropriate technology (or preloaded pins), since ACME runs over HTTP, but it's not critical to the security model.  I would suggest we add something to the Security Considerations recommending use of pinning.

**Comment by azet** [comment]
Since key and certificate generation are automated by Let's Encrypt/ACME; automating and deploying key pins seems like a logical choice. At least in my opinion. TACK does that on TLS level. HPKP does it on HTTP level. I'd actually prefer TACK but HPKP is submitted for publication, TACK is not.

**Comment by pde** [comment]
This is a feature that's on the client roadmap, but I can't see any reason why the protocol and server need to know or talk about it.  Tentatively marking this invalid unless someone can think of something the protocol or server needs to know about or do wrt pins.

**Comment by bifurcation** [comment]
Removing "invalid" tag because it does seem useful to have some advisory text here.  ("ACME servers SHOULD use HSTS/HPKP")

**Comment by martinthomson** [comment]
HSTS makes no sense here; I would rather mandate the use of HTTPS.

**Comment by azet** [comment]
HPKP makes still a lot of sense in the HTTPS context. This should be recommended ACME Server and Client-side. Client configurations should also ship HPKP if possible in my opinion.

**Comment by ekr** [comment]
I agree with MT that it would be best to just require HTTPS.

I don't have a problem with a SHOULD level requirement that clients
implement
HPKP. I would not be in favor of requiring TACK, as HPKP is the standardized
technology for this application.

**Comment by azet** [comment]
:+1:
