### ISSUE TITLE
Do not require JWS Flattened JSON Serialization

### ISSUE THREAD

**Issue by frasertweedale** [letsencrypt/acme-spec#61]
As of RESTification merge, spec states:

    The JWS MUST use the Flattened JSON Serialization

This inhibits code/library reuse.
Suppose a certain JOSE library serialises a JWS with a single signature
using the General JWS JSON Serialization Syntax. That library cannot
be used with ACME.

According to the JWS draft there is no requirement or recommendation for an implementation
to serialise a single-signature JWS using the Flattened syntax, nor is there
a requirement or recommendation to provide users a knob to control how to deal with this
ambiguous case.

So if there is no important (i.e. security) reason to have this requirement in ACME,
please remove it.

**Comment by bifurcation** [comment]
Sorry, I had actually [fixed that](https://github.com/letsencrypt/acme-spec/commit/79c51957efffeaa7689a1da66f0b725e017dc939), but forgot to push.  It is in the [version that got pushed to the IETF](https://tools.ietf.org/html/draft-barnes-acme-01).  Thanks for keeping me honest :)

**Comment by frasertweedale** [comment]
Thanks; you are welcome :)
