### ISSUE TITLE
Strategy for issuing certificates in round-robin environment.

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/acme-spec#65]
Cross post from https://github.com/letsencrypt/node-acme/issues/15

I haven't tried this yet, I just peeked at some of the node code and the question came to mind, so right now I'm just making note of it for something to come back to later.

Scenario: Consider trusted peer devices A & B. If device A requests a cert from the ACME server and the ACME server responds with a challenge to device B (via round-robin DNS) then that responding device has not yet received the token and the validation would fail.

Use case: I'm working on a distributed peer home cloud in which each app may have it's own domain name and may run on multiple authorized boxes - like a mini-CDN.

For example: https://aj.myhomemusic.com may run on a device in my home, my sister's home, and my girlfriend's home. If the power is out at my house or there's other network trouble, my custom DNS server will know that within a few seconds of the outage and will remove the device that is out from the round-robin.

This will be the first time in history that peer-to-peer encrypted https can be accomplished in a non-cost-prohibitive fashion, so I'm going to push to make sure we have support for it on Launch Day.

**Comment by titanous** [comment]
It seems like this is a non-issue with the current spec. The verification token should be distributed to all servers that the DNS name resolves to before triggering the verification.

**Comment by pde** [comment]
Under the current protocol, you can arrange (ssh or RPC) for all of the robins to pass the Challenges; turn of round-robining for the DV phase; or use a DNS Challenge method.

I can't foresee further changes to make it easier than that.
