### ISSUE TITLE
provisioning private keys on embedded devices

### ISSUE THREAD

**Issue by coolaj86** [letsencrypt/acme-spec#66]
On many embedded devices which are perfectly capable of serving https at reasonable speeds, key generation can take anywhere from 10s of seconds even to several minutes.

I know it's a stretch, but could there be consideration for allowing the server to provision the private keys in such cases?

**Comment by coolaj86** [comment]
I just ran the `demo.js` on a raspberry pi and it took 89 minutes to run (and it did complete successfully).

```
time node demo.js
5279.62user 7.17system 1:28:57elapsed 99%CPU (0avgtext+0avgdata 26496maxresident)k
352inputs+0outputs (2major+6450minor)pagefaults 0swaps
```

**Comment by schoen** [comment]
Generating keys on the server is probably not something we would want to accept as a good practice. Where CAs have done that, it seems to entail a lot of risk to the subscriber (and some risk to the CA, too).

It also puts *a lot* more trust in the CA, where many of us would like to significantly reduce the amount of trust that has to be put in the CA, through mechanisms like Certificate Transparency. When you make someone else have your private key material, there's no way that they can prove to you that they've destroyed it. Perhaps they can't even be confident themselves that they've destroyed it!

Can you try to get the Python client to run on your embedded device? If it's slow there, we can try to profile it and understand why.

It's also completely supported to port the client functionality to a new language, so if there's some language or development environment that is particularly fast on your devices, you can create an ACME client in that language or environment, and it should interoperate successfully.

**Comment by coolaj86** [comment]
I'm using node.js. After closer inspection I realized that the `forge` module they're using is, in fact, intended for use in the browser, so instead of taking maybe 30 seconds to complete the process using the native openssl bindings, it does everything in strings and optimizes for the webcrypto api, but not node's crypto api.

**Comment by coolaj86** [comment]
30 seconds is still a *really* long time.

I do understand the issues you brought up, however, I see HTTPS as being able to only guarantee transit-time privacy. The entire certificate system, as far as I can tell, is just a bunch of hoops to jump through and doesn't add any value in terms of authenticity.

Example:

If I serve a debian package to you via HTTPS we have a guarantee that eavesdroppers can't modify the package in transit and that they won't know what it is that is being transmitted. However, you still don't know that the package originated from me or debian maintainers or pirate joe until you open it up and verify the sha1 against the signature in the metadata.

If I want to guarantee to a user that a message is authentic, HTTPS isn't the right tool. PGP is the right tool.

Since HTTPS doesn't have any standard way of signing (unless there are some new headers I'm not aware of) to prove that the message itself (not just the transmission) is authentic, I'd personally rather that there were no domain checking at all and that we used PGP or something similar that can *actually* guarantee source authenticity against a DNS-like system for keys (actually, like keybase.io).

**Comment by jsha** [comment]
Server-side key generation is a wontfix for Let's Encrypt, and so probably won't be incorporated into the ACME protocol itself. However, it sounds like you are designing a home cloud infrastructure that might be an appropriate place to build in remote key generation.

Switching node-acme from forge to native Node crypto sounds fine, I'd be happy to accept that pull request.

**Comment by pde** [comment]
Someone did mention the idea of having the ACME server pass entropy down to the client to assist in secure key generation.  In theory it shouldn't really be necessary (if you have an Internet connection you should have entropy) but in practice that's probably a good idea.  Otherwise, agreeing with jsha and marking this wontfix.

**Comment by coolaj86** [comment]
Understood. Thanks for the discussion. :-D
