### ISSUE TITLE
Mechanism to express intent-to-revoke, revocation status

### ISSUE THREAD

**Issue by schoen** [letsencrypt/acme-spec#70]
For the autorenewal feature in the client, we want a way for a CA to indicate whether a cert has been revoked (which could conceivably be OCSP, except that we also want this other functionality...) and also whether a cert _is about to be revoked_. The idea there is that if the client is checking frequently enough, it can receive a warning ahead of time prior to some revocation events (typically hours before) and proceed with the renewal request before the revocation takes effect.

Should this be done in ACME? We could extend ACME to do it, or create a new protocol mechanism entirely.

Another policy question is whether the general public should be able to learn about intent-to-revoke this way, or only the affected subscriber. I was thinking that this might mean that we risk tipping off the attacker when we detect misissuance events, for example -- but in that case the attacker _is_ the subscriber, so limiting notifications to subscribers-only won't usually help anything.

(mentioning @pde)

**Comment by jcjones** [comment]
I propose we plan to provide this functionality through our existing OCSP channel. This gives us some options: 
  * We can embed something like `X-ACME-Intent` into an HTTP(s) header, and the field indicates something akin to "after this OCSP response's validity period, ACME intends to do _______".
     * This assumes we use OCSP over HTTP(s), which plays in well to CDN use.
  * Or we can embed something similar into the OCSP signed object itself as an extension. This runs afoul of the battle cry from the IETF BoF: "Read my lips, no new ASN.1!"

If we can all agree that OCSP -- somehow -- can support this, then I recommend we assume we will solve it within the OCSP channel in the future.

**Comment by bifurcation** [comment]
This seems pretty natural for an OCSP extension.  I agree that a header would be better, but would suggest something that's not ACME-specific and [doesn't use `X-`](https://tools.ietf.org/html/rfc6648), say `Planned-Revocation-Time`.

**Comment by bifurcation** [comment]
Actually, thinking on this further: This mechanism is only valid if there's latency between discovering that revocation is needed and actually revoking the cert.  That latency should be as short as possible (the BRs limit it to 24hr), so we shouldn't encourage ACME servers to increase the window by adding this mechanism.

**Comment by jsha** [comment]
The intent here is to allow the CA to revoke certificates that it would otherwise not be willing to revoke. For instance, a future event like Heartbleed or the Debian weak keys bug could mean that many certs are "potentially compromised," but not "definitely compromised." Having an intent-to-revoke mechanism would potentially reduce the pain of mass revocations enough to allow CAs to respond appropriately to those situations.

Also, I believe the intended latency of this feature is on the order of 24 hours. Subscribers that want to receive revocation notice would need to be fetching OCSP responses frequently, say once an hour.

**Comment by pde** [comment]
We believe this is a very important feature; it will give us a path to sane emergency recovery in case of an intermediate CA compromise, for instance.

Clients supporting this kind of emergency recertification/rekeying can probably do the OCSP check every hour or so without meaningfully increasing OCSP traffic volume.

**Comment by cpu** [comment]
This repository is deprecated & un-maintained. Closing this issue. If applicable, please move discussion to the replacement [IETF owned repo](https://github.com/ietf-wg-acme/acme) and the [mailing list](https://www.ietf.org/mailman/listinfo/acme).
