### ISSUE TITLE
Wrap lines

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#83]
It would make it a lot easier to read and edit markdown (and preview on github)  if we wrap lines to sensible column size (I use the "80 or 72 for long paragraphs" principle myself, and for the letsencrypt client). Thoughts? If you agree then please let me know and I'll prepare necessary PR. Probably it's best to pull in other PRs first, though.

**Comment by martinthomson** [comment]
I agree with you, though you are probably picking a fight.  I think the reason for long lines is that re-wrapping paragraphs tends to muddy diffs.  If only github were able to wrap lines in diffs, this wouldn't be as big of an issue.

**Comment by titanous** [comment]
GitHub has a document diff view that handles wrapped lines. Example: https://github.com/letsencrypt/acme-spec/pull/53/files?short_path=2e5a10b#diff-2e5a10b3cfb1002733218cd4472b40a4

**Comment by kuba** [comment]
Awesome, thanks for that info, @titanous.

@bifurcation would you be the decisive person for that matter?

**Comment by bifurcation** [comment]
I prefer leaving the long lines, for the reasons that @martinthomson states.
