### ISSUE TITLE
Certs can't be revoked with just the cert + privkey

### ISSUE THREAD

**Issue by pde** [letsencrypt/acme-spec#85]
If you ever find a cert and privkey lying around, you should be able to revoke it.  The current spec doesn't allow this, because the revoking client needs to know the Certificate URL.

I would have just edited it to require the mock "asdf" string in the Certificate URL to be the Serial Number, but because those strings are constant across a lineage of renewed certificates, I actually don't think it can be a serial number :(

**Comment by pde** [comment]
Is making the API path /acme/revoke allowed by REST?

**Comment by martinthomson** [comment]
I'd avoid baking in a uri format. One way to solve this would be to have a top-level revocation resource. Requests to that resource that are signed correctly could cause all certificates with a matching public key to be revoked. I.e., the private key should suffice.

**Comment by jsha** [comment]
Sometimes you want to revoke anything related to a certain private key (i.e. key got leaked), and sometimes you want to revoke specific certs (i.e. we issued for three names but decided we only wanted two). So we'd have to support both use cases.

Is serial number definitely constant acorss renewals? That seems non-ideal.

**Comment by pde** [comment]
Serial numbers aren't and can't be constant.  But the spec expects the Certificate URL to be [constant across renewals](https://github.com/letsencrypt/acme-spec/blob/master/draft-barnes-acme.md#certificate-refresh) :/.

**Comment by jsha** [comment]
This is fixed in my spec pull request: https://github.com/letsencrypt/acme-spec/pull/118.

@pde: I put your serial number issue in a separate issue: https://github.com/letsencrypt/acme-spec/issues/125

**Comment by ryanp-me** [comment]
#118 has been merged, so this issue can be closed.
