### ISSUE TITLE
SAN cert issuance vs. "next" Link

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#90]
Suppose client would like to request a SAN certificate for identifiers (domains) `D1` and `D2`. Client runs:

1. Get Authorization Resource for `D1`. Server returns `AR1` and "next" Link header `L1` pointing at new-certz URI.

2. Get Authorization Resource for `D2`. Server returns `AR2` and "next" Link header `L2` pointing at new-certz URI.

What if `L1 != L2`? Which link should be followed? Both? Or should `L1 != L2` case be disallowed by the protocol?

**Comment by jdkasten** [comment]
As I understand it, L1 != L2 should be/must be disallowed.  Though I agree the spec should be clear.
