### ISSUE TITLE
SAN cert issuance vs. multiple Account Key Pairs

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#91]
Consider the following scenario:

1. Client registers under two different Account Key Pairs: `K1 != K2`

2. Client gets the Authorization Resource for identifier `D1` on the `K1` account (the request is signed using `K1` JWS)

3. Client gets the Authorization Resource for identifier `D2` on the `K2` account (the request is signed using `K2` JWS).

4. Client now wants to request issuance of SAN certificate for `{D1, D2}`. Which key should be used for the signing the request?

I guess this scenario should be explicitly forbidden by the protocol.

**Comment by bifurcation** [comment]
This is just bad behavior by the client.  Neither key is authorized for both domains, so neither one can issue for both domains.
