### ISSUE TITLE
Challenges and certificates can't be requested with just a key

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#94]
This is tightly related to #85, but while @pde comment is somewhat more about a security vulnerability, there is more general problem due to the "Link" headers. Namely, client needs to persist (in the local storage) between sessions:

1. new-authz URI received in the "next" Link header of the registration (`POST new-reg`) response

2. new-cert URI received in the "next" Link header of the challenges request response (`POST new-authz`)

It's not clear from the spec, but 2. could probably be solved by polling Authorization Request for status `GET authz`, which apart from returning the AR, would be also required (or expected, depending on the answer to #93) to return the "next" Link header. Note that client still needs to know the authz URI. So, for 1., maybe `GET reg` HTTP method should also be allowed (table from section 5.1) and required to return "next" Link with the new-authz URI?

But then, how would the client know the registration address by just knowing the key? `POST find-reg` with key as the request body? Or is the client actually expected to persist all URIs?

I really think this all needs a clarification in the spec.

**Comment by bifurcation** [comment]
If all you have is a private key, and other context, you're just screwed.  But I agree that making the client persist more URIs is kind of onerous.  The right way to address that is #138, so I'm closing this as a duplicate of that.
