### ISSUE TITLE
Certificate revocation status and intent-to-revoke query mechanism

### ISSUE THREAD

**Issue by schoen** [letsencrypt/acme-spec#96]
For the renewal agent in the client, we would like to have a way to find out whether a certificate is still valid and whether the CA imminently intends to revoke it. (OCSP provides the former information, but not the latter.) The intent-to-revoke status might be triggered, for example, if the CA becomes aware that a domain has changed control.

This could then provoke a renewal attempt sooner than the otherwise-expected renewal time.

It would probably be convenient from the client's point of view to extend ACME to provide a way to query this status.

**Comment by pde** [comment]
For clarity: if there was a cert with one name, true change of control would obviously be a reason to revoke without renewal.  But if it's a cert with 10 SANs, and only one of those names has changed control, the other 9 SANs should be renewed/reissued/rekeyed before the whole cert is knocked offline by OCSP.

**Comment by schoen** [comment]
One important question is whether this mechanism belongs in ACME or elsewhere. I will plan to ask folks about that tomorrow.

**Comment by schoen** [comment]
Oops, this is actually a duplicate of #70.
