### ISSUE TITLE
Update registration HTTP response code

### ISSUE THREAD

**Issue by kuba** [letsencrypt/acme-spec#99]
Section 5.3. allows client to update registration by sending `POST` request to the registration resource URI. However, specification is unclear what HTTP code should be expected in response. FYI Boulder returns HTTP ACCEPTED (202)...

c.f. https://github.com/letsencrypt/lets-encrypt-preview/pull/325#discussion_r27526227
cc: @jdkasten

**Comment by kuba** [comment]
Also related to #89

**Comment by martinthomson** [comment]
202 is strange; just use 200 unless you have cause to provide asynchronous notification of completion (of course, please don't do that without good cause).

**Comment by bifurcation** [comment]
I agree with @martinthomson that 200 should be unnecessary.  This is a boulder issue.
